### ISSUE TITLE
Add input constraints for "Add Course" Text Box

### ISSUE THREAD

**Issue by jamisonvalentine** [cloud0x9/Schedule-Creator#14]
User should only be able to enter courses in a format similar to:

"CSC 250" or "CSC250"

![image](https://user-images.githubusercontent.com/47033011/75123342-7e193e00-5674-11ea-9b73-dc0a235f7413.png)

**Comment by ghost** [comment]
What do you think about adding a listview under the "Find Courses:" section with the courses imported from our raw courselists? (something like this https://stackoverflow.com/questions/47559491/making-a-search-bar-in-javafx
)
Each row could have the course name, class number, CRN, and maybe the schedule and we could move that "Add Course" button over to the listview so we don't have to do input checking.

**Comment by jamisonvalentine** [comment]
Yea, I was thinking of something along those lines. I guess this is still a prototype for the underlying logic. 

I like the idea of the list view providing info like the course name and number, but I was thinking the CRN could be saved for the "Schedule Generator" view.

Course View:

- User selects all courses that they're interested in taking for the given semester (but not the sections). This data is imported from the raw courselists

![image](https://user-images.githubusercontent.com/47033011/75129005-f859ba80-5694-11ea-8f7e-379cc8aecf1c.png)


Schedule Creator View:

- Each course that the user selects will be included in an Accordion (expanding menu item) and each of the course's respective sections will be listed directly under. 

- The user can then just click the "+" button to add it to the schedule and easily remove the course if they don't like the fit on the schedule

![image](https://user-images.githubusercontent.com/47033011/75128567-b891d380-5692-11ea-9ad0-a291654f3379.png)

Sorry about the blurry images... They're on LucidChart if you wanna take a closer look
