### ISSUE TITLE
Add ability to choose semester

### ISSUE THREAD

**Issue by ghost** [cloud0x9/Schedule-Creator#15]
Probably in the CourseView. Needs to switch to the correct course database in `resources/raw` and check that the currently saved courses exist for that semester

**Comment by jamisonvalentine** [comment]
I forgot to include this option in the new design so this issue is still relevant

**Comment by ghost** [comment]
I can work on it tonight unless you've started already, would we want to put it in the primary view or the scheduling view?

**Comment by jamisonvalentine** [comment]
All yours... I think the scheduling view would be better
