### ISSUE TITLE
Possible UI restructure

### ISSUE THREAD

**Issue by xsfar** [cloud0x9/Schedule-Creator#16]
I haven't looked into the UI a lot yet, but i think we should stick to one scene is or possibly two, anything more is unnecessary. There are a lot of similar projects to ours on GitHub we could take inspiration from, the best one i've seen so far is below, I think we should have something similar, just my opinion, what do you guys think?
<img width="618" alt="mainui" src="https://user-images.githubusercontent.com/42755577/75160034-5adba680-56e7-11ea-9e7d-f2b0763554cc.png">

**Comment by jamisonvalentine** [comment]
I'm not against doing it that way

**Comment by jamisonvalentine** [comment]
I would still want the ability to build a custom schedule one course at a time, though. Maybe we could have 2 scenes/views: one for building a schedule manually, the other similar to the one above for auto generated schedules

**Comment by ghost** [comment]
@cloud0x9 I agree, that is way better. We should combine the course list and schedule creation view.

What we could do is have the list of courses (which the user can search and filter) but when they select a course, every section for the course shows up in a lower box. So the user still manually chooses which section they want. 

yeah @jamisonv93 I don't know if the "schedule generation" part is that important, the most annoying thing about our current banweb system is that you can't even see your schedule until you submit it, so you have to keep track of it separately. So allowing the user to select sections and see them in the calendar could be our primary goal (IMO) - we can even let them select overlapping courses so they can add every section/class they're interested in before pruning them down.


I saw this slightly different thing from the same school, it's a webapp so you can just open it to use it:
https://digized.github.io/schedule-generator/
We could maybe make something pretty close to that UI, plus course section choices?

**Comment by jamisonvalentine** [comment]
I'm a little confused now... I thought the schedule generation was the goal of the application? It's sounds like we all still have slightly different ideas. Either that or we're not explaining them well enough... Y'all wanna spend some time getting on the same page tomorrow?

**Comment by ghost** [comment]
Sure.

**Comment by ghost** [comment]
Can I close this, or are we going to use the Scheduling view as the entry point of the GUI?

**Comment by jamisonvalentine** [comment]
I say close
