### ISSUE TITLE
Comment and Refactor

### ISSUE THREAD

**Issue by jamisonvalentine** [cloud0x9/Schedule-Creator#24]
I'm going to slow down and go back to add comments throughout and refactor where necessary. Also plan to turn my focus to getting the documentation together over the next couple of days. 

In the meantime if y'all if want add/delete anything or make any changes feel free and I'll go back and work around your code... If you have any questions about any of my code, I'll be glad to clear it up.

**Comment by ghost** [comment]
Your code is pretty readable tbh. Two questions about the user workflow:

- The search field is going to filter the "Available Courses" ComboBox, right?
- Once we implement "Get Sections", are we going to store  a separate ListView for them? I was thinking a ListView analogous to the "Selected Courses" ListView, except there's an "Add" and "Remove" button that adds the section to the calendar.

**Comment by jamisonvalentine** [comment]
Yes to both

I like responsive search from the example UI you mentioned, but I figured it would be better to start with the basic idea
https://digized.github.io/schedule-generator/
