### ISSUE TITLE
Add better boilerplate for resource and user file handling

### ISSUE THREAD

**Issue by ghost** [cloud0x9/Schedule-Creator#30]
- Resources in the src/ directory need to be accessed using their classpath 
- the user database can use normal File statements, but we should probably choose a better file hierarchy to reflect the storage location on the user's computer

- could even abstract stuff like SEMESTER_DIR and COURSELIST_DIR here if it's useful

**Comment by jamisonvalentine** [comment]
Is the user database actually necessary? It would be nice to be able to close the program and come back to the same "session" but should we leave that as an optional feature to add later? Neither of the examples we looked have that ability themselves.

**Comment by jamisonvalentine** [comment]
Nevermind that, forgot about the persistent data part of the project

**Comment by ghost** [comment]
Yeah... That's the only reason we're including that feature
