### ISSUE TITLE
saveCourse() in IDE not working

### ISSUE THREAD

**Issue by jamisonvalentine** [cloud0x9/Schedule-Creator#38]
@wrycode When I run the jar I don't have any problems, but I'm not able to save selected courses when running in NetBeans. I'm sure I'm missing something but do you know why this is the case?

**Comment by jamisonvalentine** [comment]
@wrycode Nevermind, I see what's happening now.

Currently, the selected courses are being saved to a file user_selected_courses.txt in the working directory. Should we be saving a separate selected_courses file for each semester? 

If so, would that be as simple as adding a parameter for semester in Translator.saveCourse() in Translator.getSelectedCourses() and saving to or reading from a file such as spring2020_selected_courses.txt?

**Comment by jamisonvalentine** [comment]
OR maybe
1 selected_course file which contains data for all semesters
![image](https://user-images.githubusercontent.com/47033011/76776637-661d7180-677d-11ea-9b08-17c294b2caca.png)

**Comment by ghost** [comment]
Yeah you could do it either way. Might be good to go ahead and put new methods in the adapter now.

**Comment by jamisonvalentine** [comment]
On it...

**Comment by ghost** [comment]
I'm at work now, if you hit any blocking issues that you want me to tackle (e.g. something about my code) leave me a note and I'll work on it this evening.
